# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATMultiBlocksDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ATMultiBlocksDemo
  pod 'ATMultiBlocks', :path => '../ATMultiBlocks'

end
